
---------------DATA CLEANING PROJECT-----------------

SELECT * FROM US_PRESIDENTS 

--CHANGING THE COLUMN NAME

EXEC SP_RENAME 'US_PRESIDENTS.S#NO#', 'S.NO.'
EXEC SP_RENAME 'US_PRESIDENTS.PRESIDENT', 'PRESIDENT'
EXEC SP_RENAME 'US_PRESIDENTS.PRIOR', 'PRIOR'
EXEC SP_RENAME 'US_PRESIDENTS.PARTY', 'PARTY'
EXEC SP_RENAME 'US_PRESIDENTS.VICE', 'VICE'
EXEC SP_RENAME 'US_PRESIDENTS.SALARY', 'SALARY'
EXEC SP_RENAME 'US_PRESIDENTS.DATE UPDATED', 'DATE UPDATED'
EXEC SP_RENAME 'US_PRESIDENTS.DATE CREATED', 'DATE CREATED';

--REMOVING DUPLICATES

SELECT DISTINCT * INTO PRESIDENT_LIST FROM US_PRESIDENTS

SELECT * FROM PRESIDENT_LIST

--DROPPING UNNECESSARY COLUMNS

ALTER TABLE PRESIDENT_LIST
DROP COLUMN F1,PRIOR

--TRIMMING THE COLUMN

UPDATE PRESIDENT_LIST SET VICE = TRIM(VICE)

UPDATE PRESIDENT_LIST SET VICE = REPLACE(VICE, '  ', '')

--UPDATING THE PROPER CASE OF PRESIDENT NAME

UPDATE PRESIDENT_LIST SET PRESIDENT = CONCAT(UPPER(SUBSTRING(PRESIDENT,1,1)),LOWER(SUBSTRING(PRESIDENT,2,CHARINDEX(' ',PRESIDENT)-1)),' ', 
              UPPER(SUBSTRING(PRESIDENT,CHARINDEX(' ',PRESIDENT)+1,1)),LOWER(SUBSTRING(PRESIDENT,CHARINDEX(' ',PRESIDENT)+2,LEN(PRESIDENT))))

--SPLITTING THE PARTY COLUMN

SELECT PARTY FROM PRESIDENT_LIST WHERE PARTY LIKE 'WHIG%'

UPDATE PRESIDENT_LIST SET PARTY = CASE
                                  WHEN CHARINDEX(' ', PARTY) > 0 THEN SUBSTRING(PARTY, 1, CHARINDEX(' ', PARTY) - 1)
                                  ELSE PARTY
                                  END
WHERE PARTY LIKE 'WHIG%';

--CHANGING THE DATATYPE OF DATE UPDATED AND DATE CREATED TO DATE ONLY SO THAT IT DOESN'T SHOW TIME ALONGWITH DATE.

ALTER TABLE PRESIDENT_LIST
ALTER COLUMN [DATE UPDATED] DATE

ALTER TABLE PRESIDENT_LIST
ALTER COLUMN [DATE CREATED] DATE